# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 04:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_doctorprofile_labtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='fio',
            field=models.CharField(help_text='ФИО', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='isLDAP_user',
            field=models.BooleanField(default=False, help_text='Флаг, показывающий, что это импортированый из LDAP пользователь'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='labtype',
            field=models.IntegerField(blank=True, choices=[(0, 'Не из лаборатории'), (1, 'Врач'), (2, 'Лаборант')], default=0, help_text='Категория профиля для лаборатории'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='podrazileniye',
            field=models.ForeignKey(blank=True, help_text='Подразделение', null=True, on_delete=django.db.models.deletion.CASCADE, to='podrazdeleniya.Podrazdeleniya'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Ссылка на Django-аккаунт', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
