from django.urls import path
from . import views

urlpatterns = [
    path('templates', views.get_researches_templates),
    path('all', views.get_researches),
    path('last-used', views.last_used_researches),
    path('by-department', views.researches_by_department),
    path('params', views.researches_params),
    path('update', views.researches_update),
    path('details', views.researches_details),
    path('paraclinic_details', views.paraclinic_details),
    path('hosp-service-details', views.hospital_service_details),
    path('fast-templates', views.fast_templates),
    path('fast-template-data', views.fast_template_data),
    path('fast-template-save', views.fast_template_save),
    path('fraction-title', views.fraction_title),
    path('field-title', views.field_title),
    path('fields-and-groups-titles', views.fields_and_groups_titles),
    path('descriptive-research', views.descriptive_research),
    path('profiles-research', views.profiles_research),
    path('research-dispensary', views.research_dispensary),
    path('research-specialities', views.research_specialities),
    path('save-dispensary-data', views.save_dispensary_data),
    path('load-research-by-diagnos', views.load_research_by_diagnos),
    path('by-direction-params', views.by_direction_params),
    path('get-direction-params', views.get_direction_params),
    path('localization', views.localization),
    path('localization/save', views.localization_save),
    path('required-stattalon-fields', views.required_stattalon_fields),
    path('researches-required-stattalon-fields', views.researches_required_stattalon_fields),
    path('help-link-field', views.help_link_field),
    path('research-groups-by-laboratory', views.research_groups_by_laboratory),
    path('group-as-json', views.group_as_json),
    path('tube-related-data', views.tube_related_data),
    path('existing-tubes-relation', views.get_existing_tubes_relation),
    path('tube-related-data/update', views.tube_related_data_update),
    path('research-performer-save', views.research_performer_save),
    path('get-research-performer', views.get_research_performer),
    path('get-research-permissions', views.get_research_permissions),
    path('save-research-permissions', views.save_research_permissions),
]
