export const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS';

export const GET_BASES = 'GET_BASES';

export const GET_TEMPLATES = 'GET_TEMPLATES';
export const GET_RESEARCHES = 'GET_RESEARCHES';

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_DIRECTIVE_FROM = 'GET_DIRECTIVE_FROM';

export const ENABLE_LOADING = 'ENABLE_LOADING';
export const INC_LOADING = 'INC_LOADING';
export const DISABLE_LOADING = 'DISABLE_LOADING';
export const DEC_LOADING = 'DEC_LOADING';
export const SET_LOADER_IN_HEADER = 'SET_LOADER_IN_HEADER';

export const CHANGE_STATUS_MENU_ANESTHESIA = 'CHANGE_STATUS_MENU_ANESTHESIA';

export const LOAD_HOSPITALS = 'LOAD_HOSPITALS';
