export const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS';

export const GET_BASES = 'GET_BASES';

export const GET_TEMPLATES = 'GET_TEMPLATES';
export const GET_RESEARCHES = 'GET_RESEARCHES';
export const GET_LAST_USED_RESEARCHES = 'GET_LAST_USED_RESEARCHES';

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_DIRECTIVE_FROM = 'GET_DIRECTIVE_FROM';

export const ENABLE_LOADING = 'ENABLE_LOADING';
export const INC_LOADING = 'INC_LOADING';
export const DISABLE_LOADING = 'DISABLE_LOADING';
export const DEC_LOADING = 'DEC_LOADING';
export const SET_LOADER_IN_HEADER = 'SET_LOADER_IN_HEADER';
export const RESET_LOADING = 'RESET_LOADING';

export const RESET_G_LOADING = 'RESET_G_LOADING';
export const INC_G_LOADING = 'INC_G_LOADING';
export const DEC_G_LOADING = 'DEC_G_LOADING';

export const CHANGE_STATUS_MENU_ANESTHESIA = 'CHANGE_STATUS_MENU_ANESTHESIA';

export const LOAD_HOSPITALS = 'LOAD_HOSPITALS';

export const LOAD_PERMANENT_DIRECTORY = 'LOAD_PERMANENT_DIRECTORY';

export const HAS_NEW_VERSION = 'HAS_NEW_VERSION';

export const LOAD_REQUIRED_STATTALON_FIELDS = 'LOAD_REQUIRED_STATTALON_FIELDS';

export const LOAD_RESEARCHES_PK_REQUIRED_STATTALON_FIELDS = 'LOAD_RESEARCHES_PK_REQUIRED_STATTALON_FIELDS';

export const CHATS_LOAD_DEPARTMENTS = 'CHATS_LOAD_DEPARTMENTS';
export const CHATS_MESSAGES_COUNT = 'CHATS_MESSAGES_COUNT';
export const CHATS_OPEN_DIALOG = 'CHATS_OPEN_DIALOG';
export const CHATS_OPEN_DIALOG_BY_ID = 'CHATS_OPEN_DIALOG_BY_ID';
export const CHATS_CLOSE_DIALOG = 'CHATS_CLOSE_DIALOG';
export const CHATS_CLEAR_STATE = 'CHATS_CLEAR_STATE';
export const CHATS_GET_NOTIFY_TOKEN = 'CHATS_GET_NOTIFY_TOKEN';
export const CHATS_NOTIFY = 'CHATS_NOTIFY';
export const CHATS_SET_DISABLE_ALERTS = 'CHATS_SET_DISABLE_ALERTS';

export const PRINT_QUEUE_ADD_ELEMENT = 'PRINT_QUEUE_ADD_ELEMENT';
export const PRINT_QUEUE_DEL_ELEMENT = 'PRINT_QUEUE_DEL_ELEMENT';
export const PRINT_QUEUE_INIT = 'PRINT_QUEUE_INIT';
export const PRINT_QUEUE_SAVE_LS = 'PRINT_QUEUE_SAVE_LS';
export const PRINT_QUEUE_CHANGE_ORDER = 'PRINT_QUEUE_CHANGE_ORDER';
export const PRINT_QUEUE_FLUSH = 'PRINT_QUEUE_FLUSH';

export const EDIT_OPEN = 'EDIT_OPEN';
export const EDIT_HIDE = 'EDIT_HIDE';
export const EDIT_SAVED_OBJECT = 'EDIT_SAVED_OBJECT';
