export const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS'
export const UPDATE_DEPARTMENTS = 'UPDATE_DEPARTMENTS'

export const GET_BASES = 'GET_BASES'

export const GET_TEMPLATES = 'GET_TEMPLATES'
export const GET_RESEARCHES = 'GET_RESEARCHES'

export const GET_USER_DATA = 'GET_USER_DATA'
