export const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS';

export const GET_BASES = 'GET_BASES';

export const GET_TEMPLATES = 'GET_TEMPLATES';
export const GET_RESEARCHES = 'GET_RESEARCHES';
export const GET_LAST_USED_RESEARCHES = 'GET_LAST_USED_RESEARCHES';

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_DIRECTIVE_FROM = 'GET_DIRECTIVE_FROM';

export const ENABLE_LOADING = 'ENABLE_LOADING';
export const INC_LOADING = 'INC_LOADING';
export const DISABLE_LOADING = 'DISABLE_LOADING';
export const DEC_LOADING = 'DEC_LOADING';
export const SET_LOADER_IN_HEADER = 'SET_LOADER_IN_HEADER';
export const RESET_LOADING = 'RESET_LOADING';

export const RESET_G_LOADING = 'RESET_G_LOADING';
export const INC_G_LOADING = 'INC_G_LOADING';
export const DEC_G_LOADING = 'DEC_G_LOADING';

export const CHANGE_STATUS_MENU_ANESTHESIA = 'CHANGE_STATUS_MENU_ANESTHESIA';

export const LOAD_HOSPITALS = 'LOAD_HOSPITALS';

export const LOAD_PERMANENT_DIRECTORY = 'LOAD_PERMANENT_DIRECTORY';

export const HAS_NEW_VERSION = 'HAS_NEW_VERSION';

export const LOAD_REQUIRED_STATTALON_FIELDS = 'LOAD_REQUIRED_STATTALON_FIELDS';

export const LOAD_RESEARCHES_PK_REQUIRED_STATTALON_FIELDS = 'LOAD_RESEARCHES_PK_REQUIRED_STATTALON_FIELDS';
