export const UPDATE_DEPARTMENTS = 'UPDATE_DEPARTMENTS'
export const UPDATE_OLD_DEPARTMENTS = 'UPDATE_OLD_DEPARTMENTS'
export const SET_UPDATED_DEPARTMENT = 'SET_UPDATED_DEPARTMENT'
export const SET_CAN_EDIT = 'SET_CAN_EDIT'
export const SET_TYPES = 'SET_TYPES'

export const UPDATE_BASES = 'UPDATE_BASES'
