export const UPDATE_DEPARTMENTS = 'UPDATE_DEPARTMENTS';
export const UPDATE_OLD_DEPARTMENTS = 'UPDATE_OLD_DEPARTMENTS';
export const SET_UPDATED_DEPARTMENT = 'SET_UPDATED_DEPARTMENT';
export const SET_CAN_EDIT = 'SET_CAN_EDIT';
export const SET_TYPES = 'SET_TYPES';

export const UPDATE_BASES = 'UPDATE_BASES';

export const UPDATE_TEMPLATES = 'UPDATE_TEMPLATES';
export const SET_TEMPLATES_LOADED = 'SET_TEMPLATES_LOADED';
export const UPDATE_RESEARCHES = 'UPDATE_RESEARCHES';
export const UPDATE_TUBES = 'UPDATE_TUBES';

export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_DIRECTIVE_FROM = 'SET_DIRECTIVE_FROM';

export const SET_LOADING = 'SET_LOADING';
export const SET_LOADING_COUNTER = 'SET_LOADING_COUNTER';
export const SET_LOADER_IN_HEADER = 'SET_LOADER_IN_HEADER';

export const TOGGLE_ANESTHESIA_MENU_SHOW = 'TOGGLE_ANESTHESIA_MENU_SHOW';

export const SET_HOSPITALS = 'SET_HOSPITALS';
