export const UPDATE_DEPARTMENTS = 'UPDATE_DEPARTMENTS';
export const UPDATE_OLD_DEPARTMENTS = 'UPDATE_OLD_DEPARTMENTS';
export const SET_UPDATED_DEPARTMENT = 'SET_UPDATED_DEPARTMENT';
export const SET_CAN_EDIT = 'SET_CAN_EDIT';
export const SET_TYPES = 'SET_TYPES';

export const UPDATE_BASES = 'UPDATE_BASES';

export const UPDATE_TEMPLATES = 'UPDATE_TEMPLATES';
export const SET_TEMPLATES_LOADED = 'SET_TEMPLATES_LOADED';
export const UPDATE_RESEARCHES = 'UPDATE_RESEARCHES';
export const ADD_RESEARCHES = 'ADD_RESEARCHES';
export const UPDATE_TUBES = 'UPDATE_TUBES';

export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_SEMI_LAZY_STATE = 'SET_SEMI_LAZY_STATE';
export const SET_MENU = 'SET_MENU';
export const SET_DIRECTIVE_FROM = 'SET_DIRECTIVE_FROM';

export const SET_LOADING = 'SET_LOADING';
export const SET_LOADING_COUNTER = 'SET_LOADING_COUNTER';
export const SET_LOADER_IN_HEADER = 'SET_LOADER_IN_HEADER';

export const SET_G_LOADING_COUNTER = 'SET_G_LOADING_COUNTER';

export const TOGGLE_ANESTHESIA_MENU_SHOW = 'TOGGLE_ANESTHESIA_MENU_SHOW';

export const SET_HOSPITALS = 'SET_HOSPITALS';

export const SET_PERMANENT_DIRECTORY = 'SET_PERMANENT_DIRECTORY';

export const SET_HAS_NEW_VERSION = 'SET_HAS_NEW_VERSION';

export const SET_REQUIRED_STATTALON_FIELDS = 'SET_REQUIRED_STATTALON_FIELDS';

export const SET_RESEARCHES_PK_REQUIRED_STATTALON_FIELDS = 'SET_RESEARCHES_PK_REQUIRED_STATTALON_FIELDS';

export const CHATS_SET_DEPARTMENTS = 'CHATS_SET_DEPARTMENTS';
export const CHATS_SET_LOADING = 'CHATS_SET_LOADING';
export const CHATS_OPEN_DIALOG = 'CHATS_OPEN_DIALOG';
export const CHATS_CLOSE_DIALOG = 'CHATS_CLOSE_DIALOG';
export const CHATS_CLEAR_STATE = 'CHATS_CLEAR_STATE';
export const CHATS_SET_MESSAGES_COUNT = 'CHATS_SET_MESSAGES_COUNT';
export const CHATS_SET_NOTIFY_TOKEN = 'CHATS_SET_NOTIFY_TOKEN';
export const CHATS_SET_DISABLE_ALERTS = 'CHATS_SET_DISABLE_ALERTS';

export const PRINT_QUEUE_ADD_ELEMENT = 'PRINT_QUEUE_ADD_ELEMENT';
export const PRINT_QUEUE_DEL_ELEMENT = 'PRINT_QUEUE_DEL_ELEMENT';
export const PRINT_QUEUE_REPLACE_STATE = 'PRINT_QUEUE_REPLACE_STATE';
export const PRINT_QUEUE_CHANGE_ORDER = 'PRINT_QUEUE_CHANGE_ORDER';
export const PRINT_QUEUE_FLUSH = 'PRINT_QUEUE_FLUSH';

export const EDIT_SET_STATE = 'EDIT_SET_STATE';
export const EDIT_CLEAR_STATE = 'EDIT_CLEAR_STATE';

export const SET_PREV_EDIT_ID = 'SET_PREV_EDIT_ID';

export const OPEN_SHIFT = 'OPEN_SHIFT';
export const CLOSE_SHIFT = 'CLOSE_SHIFT';
