# Generated by Django 2.0.1 on 2018-01-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('s', 'string'), ('i', 'integer'), ('f', 'float'), ('b', 'boolean')], max_length=1)),
                ('hide_value_in_list', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
    ]
