# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0030_issledovaniya_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='is_normal',
            field=models.CharField(blank=True, default='', help_text='Это норма?', max_length=255, null=True),
        ),
    ]
