# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0032_auto_20161107_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='issledovaniya',
            name='need_comment',
            field=models.BooleanField(default=False, blank=True, help_text='Возможность оставить комментарий лабораторией'),
        ),
    ]
