# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0033_auto_20161107_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issledovaniya',
            name='need_comment',
        ),
    ]
