BED_TYPE_STANDARD = 0
BED_TYPE_REANIMATION = 1
BED_TYPE_OXYGEN = 2

BED_TYPES = (
    (BED_TYPE_STANDARD, 'Обычная'),
    (BED_TYPE_REANIMATION, 'Реанимационная'),
    (BED_TYPE_OXYGEN, 'Кислородная'),
)
