constructor_help_message = [
    {"label": "Справка", "param": "", "value": "для ссылочного типа: \"ПОЛЕ ОПИСАТЕЛЬНОГО РЕЗУЛЬТАТА БЕЗ ЗАГОЛОВКА\""},
    {"label": "-", "param": "%work_place", "value": "Место работы пациента"},
    {"label": "-", "param": "%hospital", "value": "Текущая медицинская организация"},
    {
        "label": "-",
        "param": "%parent_dir_data",
        "value": "Для экспертизы. Сохранить данные из протокола, для к-рого проводится Экспертиза " "(Пациент-ФИО}. Д/р}. Полис. СНИЛС. Протокол. Номер",
    },
    {"label": "-", "param": "%main_address", "value": "Адрес регистрации пациента"},
    {"label": "-", "param": "%mother_full_main_address", "value": "Адрес регистрации матери по ФИАС"},
    {"label": "-", "param": "%full_main_address", "value": "Адрес регистрации пациента по ФИАС"},
    {"label": "-", "param": "%docprofile", "value": "Текущий пользователь"},
    {"label": "-", "param": "%doc_position", "value": "Должность текущего пользователя"},
    {"label": "-", "param": "%patient_fio", "value": "ФИО пациента"},
    {"label": "-", "param": "%patient_family", "value": "Только фамилия пациента"},
    {"label": "-", "param": "%patient_name", "value": "Только имя пациента"},
    {"label": "-", "param": "%patient_patronymic", "value": "Только отчество пациента"},
    {"label": "-", "param": "%mother_family", "value": "Только фамилия матери"},
    {"label": "-", "param": "%mother_name", "value": "Только имя матери"},
    {"label": "-", "param": "%mother_patronymic", "value": "Только отчество матери"},
    {"label": "-", "param": "%patient_born", "value": "Дата рождения пациента"},
    {"label": "-", "param": "%mother_born", "value": "Дата рождения матери"},
    {"label": "-", "param": "%snils", "value": "СНИЛС"},
    {"label": "-", "param": "%mother_snils", "value": "СНИЛС-матери"},
    {"label": "-", "param": "%polis_enp", "value": "ПОЛИС-ЕНП пациента"},
    {"label": "-", "param": "%mother_polis_enp", "value": "ПОЛИС-ЕНП матери"},
    {"label": "-", "param": "%tfoms-attachment", "value": "Прикрепление пациента"},
    {"label": "-", "param": "%fact_address", "value": "Фактический адрес пациента"},
    {"label": "-", "param": "%full_fact_address", "value": "Фактический адрес пациента по ФИАС"},
    {"label": "-", "param": "%phone", "value": "Телефон пациента"},
    {"label": "-", "param": "%current_manager", "value": "Текущий руководитель МО"},
    {"label": "-", "param": "%work_position", "value": "Должность пациента из карты"},
    {"label": "-", "param": "%work_department", "value": "Подразделение пациента из карты "},
    {"label": "-", "param": "%harmful_factor", "value": "Факторы вредности пациента из карты"},
    {"label": "-", "param": "%harmfull_factors", "value": "Факторы вредности из отдельной модели"},
    {"label": "-", "param": "%proto_operation", "value": "Сведения об операциях в стационарном случае"},
    {"label": "-", "param": "%directionparam:11212", "value": "Из параметра Направление ссылка на id-поля 11212"},
    {"label": "-", "param": "%direction#date_visit_date", "value": "Дата регистрации направления/посещения пациента"},
    {"label": "-", "param": "%direction#time_visit_date", "value": "Время регистрации направления/посещения пациента"},
    {"label": "-", "param": "%prevDirectionFieldValue:1212", "value": "Предыдущее значение"},
    {"label": "-", "param": "%current_year#12121", "value": "Последнее значение поля в текущем году"},
    {"label": "-", "param": "%months_ago#12121#", "value": "Последнее значение поля за предыдущие 5 месяце"},
    {"label": "-", "param": "%current_hosp#12121", "value": "Искать в рамках текущего отделения"},
    {"label": "-", "param": "%root_hosp#12121#", "value": "Искать в рамках текущей госпитализации по всем отделениям"},
    {"label": "-", "param": "%vital_param#code#current_hosp", "value": "Контролируемый(витальный) параметр пациента в текущем отделении"},
    {"label": "-", "param": "%vital_param#code#root_hosp", "value": "Контролируемый(витальный) параметр пациента в рамках текущей госпитализации по всем отделениям"},
    {
        "label": "-",
        "param": "%control_param#code#period#find_val",
        "value": "Контролируемый(витальный) параметр пациента#код пар-ра#год с какого искать#искомое значение (Возврат  'Да', если соотв условию искомого значения)",
    },
    {"label": "-", "param": "\"|\"", "value": "поиск с применением логического 'ИЛИ' пока не найдет первое"},
    {"label": "-", "param": "\"&\"", "value": "поиск с применением логического 'И' по всем ссылочным полям"},
    {"label": "-", "param": "\"@\"", "value": "поиск по ссылке на группу"},
    {"label": "Справка", "param": "  ", "value": "для  типа: \"РАССЧЕТНОЕ\""},
    {"label": "-", "param": "[_sex_]", "value": "пол пациента"},
    {"label": "-", "param": "[_age_]", "value": "возраст пациента"},
    {"label": "-", "param": "правила", "value": "{121212} - в фигурных скобках записываем ссылку на id-поля далее правила синтаксиса JAVASCRIPT. Аналогично для ВИДИМОСТИ и КОНТРОЛя"},
]
