name: Py (min version) 3.8 Django testing

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: 'COMMIT_${SHORT_SHA}'

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: l2
          POSTGRES_PASSWORD: 123456
          POSTGRES_USER: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install mupdf
      run: sudo apt install libmupdf-dev
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-tests.txt
    - name: Migrate
      run: |
        python manage.py migrate
    - name: Make migrations
      run: |
        python manage.py makemigrations
    - name: Migrate
      run: |
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test
