# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20160817_1250'),
        ('directory', '0021_auto_20160707_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researches', models.ManyToManyField(to='directory.Researches')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DoctorProfile')),
            ],
        )
    ]
